# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selekcia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='linka',
        ),
        migrations.AddField(
            model_name='produkt',
            name='obrlinka',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='shoplinka',
            field=models.TextField(default='n/a'),
        ),
    ]
