# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selekcia', '0002_auto_20160818_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='obrlinka',
            field=models.CharField(default='n/a', max_length=600),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='shoplinka',
            field=models.CharField(default='n/a', max_length=600),
        ),
    ]
