# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Selekcia', '0003_auto_20160818_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='autor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
