# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selekcia', '0004_auto_20160818_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='autor',
        ),
    ]
