# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Selekcia', '0007_produkt_mena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('vyrobca', models.CharField(default='n/a', max_length=100)),
                ('cena', models.FloatField(default=0)),
                ('mena', models.CharField(default='EUR', max_length=3)),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('miesto', models.CharField(max_length=200)),
            ],
        ),
    ]
