# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selekcia', '0008_ceny'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceny',
            name='obrlinka',
            field=models.CharField(default='n/a', max_length=600),
        ),
    ]
