# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Selekcia', '0009_ceny_obrlinka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceny',
            name='datum',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
